version: '3.8'

services:
  redisdb:
    image: "redis:6-alpine"
    container_name: redis-server
    ports:
      - "6379:6379"
    command: redis-server --requirepass mypass
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf