openapi: 3.0.0
info:
  version: "1.0-DRAFT-2021-11-21"
  title: Stocks App
  description: |
    Application to receive and manipulate stock information.

servers:
  - url: /stocks-mgmt

tags:
  - name: Stocks Application
    description: Stocks application management

paths:
  /external/v1/stocks:
    get:
      summary: Return a list viewable stocks
      operationId: getAllViewableStocks
      responses:
        '200':
          description: All viewable stocks for user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebStocksResponse"
        default:
          description: An unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WebError"

components:
  schemas:
    WebStocksResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        stocks:
          type: array
          items:
            $ref: "#/components/schemas/WebStock"

    WebStock:
      type: object
      properties:
        id:
          description: "The id for this stock."
          type: string
          format: uuid
        name:
          type: string
          description: "The name of the stock."
        price:
          type: integer
          format: int64
          description: "The current price in cents."
        currencyValue:
          type: string
          enum:
            - EURO_CENT
            - US_DOLLAR_CENT

    WebError:
      required:
        - httpCode
        - errorMessage
      properties:
        httpCode:
          type: integer
          format: int32
        errorMessage:
          type: string